title: NÅ ER DET ALVOR - Mye mer enn en podcast
lang: nb
email: eplehans@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://naerdetalvor.no" # the base hostname & protocol for your site, e.g. http://example.com
seo_keywords: podcast foredrag løpecoaching ultraløping terrengløping workshop inspirasjon løpereiser ultra trener coach skyrunning bedriftpodcast 

# Build settings

destination: docs
plugins:
  - jekyll-feed
  
# permalink: pretty
markdown: kramdown

# Sass settings
sass:
  sass_dir: style
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/